// This file is auto-generated by @hey-api/openapi-ts

/**
 * Tool represents a tool entity
 */
export type ModelsTool = {
    category?: string;
    name?: string;
    url?: string;
};

/**
 * User represents a user entity
 */
export type ModelsUser = {
    password?: string;
    username?: string;
};

export type NetworkResponse = {
    /**
     * 响应码
     */
    code?: NetworkStatusCode;
    /**
     * 响应数据(可以为空)
     */
    data?: unknown;
    /**
     * 响应描述
     */
    message?: string;
    /**
     * 响应时间戳
     */
    time?: number;
};

export type NetworkStatusCode = 200 | 400 | 401 | 403 | 404 | 500 | 501 | 502 | 503;

export const NetworkStatusCode = {
    STATUS_OK: 200,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_FORBIDDEN: 403,
    STATUS_NOT_FOUND: 404,
    STATUS_INTERNAL_SERVER_ERROR: 500,
    STATUS_NOT_IMPLEMENTED: 501,
    STATUS_BAD_GATEWAY: 502,
    STATUS_SERVICE_UNAVAILABLE: 503
} as const;

export type PostLoginData = {
    /**
     * 用户名密码登录
     */
    body: ModelsUser;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: NetworkResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: NetworkResponse;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type GetToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tools';
};

export type GetToolsErrors = {
    /**
     * 参数错误！
     */
    400: string;
    /**
     * 服务器错误！
     */
    500: string;
};

export type GetToolsError = GetToolsErrors[keyof GetToolsErrors];

export type GetToolsResponses = {
    /**
     * OK
     */
    200: NetworkResponse;
};

export type GetToolsResponse = GetToolsResponses[keyof GetToolsResponses];

export type PostToolsData = {
    /**
     * 工具新增
     */
    body: ModelsTool;
    path?: never;
    query?: never;
    url: '/tools';
};

export type PostToolsErrors = {
    /**
     * 参数错误！
     */
    400: string;
    /**
     * 服务器错误！
     */
    500: string;
};

export type PostToolsError = PostToolsErrors[keyof PostToolsErrors];

export type PostToolsResponses = {
    /**
     * OK
     */
    200: NetworkResponse;
};

export type PostToolsResponse = PostToolsResponses[keyof PostToolsResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * 参数错误！
     */
    400: string;
    /**
     * 服务器错误！
     */
    500: string;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * OK
     */
    200: NetworkResponse;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    /**
     * 用户新增
     */
    body: ModelsUser;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * 参数错误！
     */
    400: string;
    /**
     * 服务器错误！
     */
    500: string;
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * OK
     */
    200: NetworkResponse;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8081/v1' | 'https://127.0.0.1:8081/v1' | (string & {});
};