name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build And Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_IMAGE }}:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Login
        uses: appleboy/ssh-action@v1.0.3
        env:
          REGISTRY: ${{ secrets.ACR_REGISTRY }}
          USERNAME: ${{ secrets.ACR_REGISTRY }}
          PASSWORD: ${{ secrets.ACR_TOKEN }}
          IMAGE: ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_IMAGE }}:latest
          CONTAINER: ${{ secrets.ACR_IMAGE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: IMAGE,CONTAINER,REGISTRY,USERNAME,PASSWORD
          script: |
            if docker ps -a | grep "$CONTAINER"; then
             docker stop $CONTAINER && docker rm $CONTAINER && docker rmi $IMAGE
            fi
            docker login --username=$USERNAME --password=$PASSWORD $REGISTRY
            docker pull $IMAGE
            docker run -d --name $CONTAINER -p 80:80 -p 443:443 -v /data/nginx-certs:/etc/nginx/certs $IMAGE
